version: '3.8'

networks:
  teleportc:

services:

  db:
    image: postgres:13.3
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: "teleportc" #it must be from vault
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    networks:
        - teleportc

  distance:
    container_name: distance
    build:
      dockerfile: dockerfile
      context: .
    ports: 
      - 5000:80
    networks:
      - teleportc
